{
 "title": "Retail • Postgres (analytics / airflow / mlflow)",
 "tags": [
  "retail",
  "postgres",
  "exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": "postgres-analytics,postgres-airflow,postgres-mlflow"
   }
  ]
 },
 "panels": [
  {
   "title": "Exporter UP",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 7 },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Connections (numbackends)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 7 },
   "targets": [
    {
     "expr": "sum by(job) (pg_stat_database_numbackends{job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Transactions commit/s",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 7 },
   "targets": [
    {
     "expr": "sum by(job) (rate(pg_stat_database_xact_commit{job=~\"$job\"}[2m]))"
    }
   ]
  },
  {
   "title": "Blocks read time (ms/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 7, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(job) (rate(pg_stat_database_blk_read_time{job=~\"$job\"}[2m]))"
    }
   ]
  },
  {
   "title": "Blocks write time (ms/s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 7, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by(job) (rate(pg_stat_database_blk_write_time{job=~\"$job\"}[2m]))"
    }
   ]
  }
 ]
}